"""SNAPHU phase unwrapping interface.

Generates SNAPHU configuration files, executes the unwrapping, and
reads back results. This replaces both SNAP's SnaphuExport/SnaphuImport
operators and the fragile conf-file parsing in the original pipeline.

SNAPHU is configured in DEFO (deformation) mode for subsidence
monitoring, which uses a cost function appropriate for spatially
correlated phase signals from ground deformation.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import textwrap
from pathlib import Path
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)

_SNAPHU_CONF_TEMPLATE = textwrap.dedent("""\
    # SNAPHU configuration for peatland subsidence unwrapping
    # Generated by PeatGuard pipeline

    INFILE          {phase_file}
    LINELENGTH      {width}
    OUTFILE         {unwrapped_file}
    COSTINFILE      {coherence_file}

    STATCOSTMODE    {cost_mode}
    INFILEFORMAT    COMPLEX_DATA
    CORRFILEFORMAT  FLOAT_DATA
    OUTFILEFORMAT   FLOAT_DATA

    # Tile processing for large scenes
    NTILEROW        {n_tile_row}
    NTILECOL        {n_tile_col}
    ROWOVRLP        200
    COLOVRLP        200
    NPROC           {n_proc}

    # Deformation parameters
    DEFOMAX_CYCLE   {defomax}
    CORRTHRESHOLD   {corr_threshold}
""")


def generate_snaphu_config(
    phase_file: Path,
    coherence_file: Path,
    output_file: Path,
    width: int,
    config_path: Path,
    cost_mode: str = "DEFO",
    n_tile_row: int = 1,
    n_tile_col: int = 1,
    n_proc: int = 1,
    defomax: float = 1.2,
    corr_threshold: float = 0.1,
) -> Path:
    """Generate a SNAPHU configuration file.

    Args:
        phase_file: Path to wrapped phase (complex float, BIL format).
        coherence_file: Path to coherence (float, BIL format).
        output_file: Path for unwrapped output.
        width: Image width in pixels (line length).
        config_path: Path to write the conf file.
        cost_mode: Cost mode ('DEFO', 'SMOOTH', 'TOPO').
        n_tile_row: Number of tiles in row direction.
        n_tile_col: Number of tiles in column direction.
        n_proc: Number of parallel processes for tiled unwrapping.
        defomax: Maximum expected deformation in cycles per pixel.
        corr_threshold: Minimum coherence for unwrapping.

    Returns:
        Path to the generated configuration file.
    """
    conf_content = _SNAPHU_CONF_TEMPLATE.format(
        phase_file=phase_file.name,
        coherence_file=coherence_file.name,
        unwrapped_file=output_file.name,
        width=width,
        cost_mode=cost_mode,
        n_tile_row=n_tile_row,
        n_tile_col=n_tile_col,
        n_proc=n_proc,
        defomax=defomax,
        corr_threshold=corr_threshold,
    )

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(conf_content)
    logger.info("Generated SNAPHU config: %s", config_path)
    return config_path


def run_snaphu(
    config_path: Path,
    work_dir: Optional[Path] = None,
    snaphu_bin: str = "snaphu",
    timeout_seconds: int = 3600,
) -> None:
    """Execute SNAPHU phase unwrapping.

    Args:
        config_path: Path to the SNAPHU configuration file.
        work_dir: Working directory for SNAPHU. Defaults to config file's parent.
        snaphu_bin: Path to the SNAPHU binary.
        timeout_seconds: Maximum execution time in seconds.

    Raises:
        RuntimeError: If SNAPHU exits with a non-zero return code.
        FileNotFoundError: If the SNAPHU binary is not found.
    """
    if work_dir is None:
        work_dir = config_path.parent

    if not shutil.which(snaphu_bin):
        raise FileNotFoundError(
            f"SNAPHU binary not found: {snaphu_bin}. "
            "Install SNAPHU or provide the correct path."
        )

    cmd = [snaphu_bin, "-f", config_path.name]
    logger.info("Running SNAPHU: %s (in %s)", " ".join(cmd), work_dir)

    result = subprocess.run(
        cmd,
        cwd=str(work_dir),
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
    )

    if result.returncode != 0:
        logger.error("SNAPHU failed:\n%s", result.stderr[-2000:])
        raise RuntimeError(f"SNAPHU failed with return code {result.returncode}")

    logger.info("SNAPHU completed successfully")


def prepare_snaphu_inputs(
    interferogram: np.ndarray,
    coherence: np.ndarray,
    work_dir: Path,
) -> tuple[Path, Path, int]:
    """Write interferogram and coherence to flat binary files for SNAPHU.

    SNAPHU expects flat binary files in BIL (Band Interleaved by Line)
    format. The interferogram is written as complex float32 and
    coherence as float32.

    Args:
        interferogram: 2D complex array (filtered wrapped phase).
        coherence: 2D float array (interferometric coherence, 0-1).
        work_dir: Directory for SNAPHU working files.

    Returns:
        Tuple of (phase_path, coherence_path, width).
    """
    work_dir.mkdir(parents=True, exist_ok=True)

    phase_path = work_dir / "wrapped_phase.int"
    coh_path = work_dir / "coherence.cor"

    interferogram.astype(np.complex64).tofile(str(phase_path))
    coherence.astype(np.float32).tofile(str(coh_path))

    width = interferogram.shape[1]
    logger.info(
        "Prepared SNAPHU inputs: %dx%d, phase=%s, coh=%s",
        interferogram.shape[0],
        width,
        phase_path.name,
        coh_path.name,
    )
    return phase_path, coh_path, width


def read_unwrapped_phase(
    output_path: Path,
    height: int,
    width: int,
) -> np.ndarray:
    """Read SNAPHU's unwrapped phase output.

    Args:
        output_path: Path to the unwrapped phase flat binary.
        height: Image height in pixels.
        width: Image width in pixels.

    Returns:
        2D float32 array of unwrapped phase in radians.
    """
    data = np.fromfile(str(output_path), dtype=np.float32)
    unwrapped = data.reshape(height, width)
    logger.info(
        "Read unwrapped phase: %dx%d, range=[%.2f, %.2f] rad",
        height,
        width,
        np.nanmin(unwrapped),
        np.nanmax(unwrapped),
    )
    return unwrapped


def unwrap_interferogram(
    interferogram: np.ndarray,
    coherence: np.ndarray,
    work_dir: Path,
    cost_mode: str = "DEFO",
    corr_threshold: float = 0.1,
    snaphu_bin: str = "snaphu",
) -> np.ndarray:
    """Complete unwrapping workflow: prepare, configure, run, read.

    This is the high-level entry point that handles the full SNAPHU
    unwrapping cycle for a single interferogram.

    Args:
        interferogram: Complex wrapped interferogram.
        coherence: Coherence array (0-1).
        work_dir: Working directory for SNAPHU files.
        cost_mode: SNAPHU cost mode.
        corr_threshold: Minimum coherence threshold.
        snaphu_bin: Path to SNAPHU binary.

    Returns:
        2D array of unwrapped phase in radians.
    """
    height, width = interferogram.shape

    # Prepare binary inputs
    phase_path, coh_path, _ = prepare_snaphu_inputs(
        interferogram, coherence, work_dir
    )

    # Output file
    unwrapped_path = work_dir / "unwrapped_phase.unw"

    # Determine tiling for large scenes
    n_tile_row = max(1, height // 2000)
    n_tile_col = max(1, width // 2000)
    n_proc = min(n_tile_row * n_tile_col, os.cpu_count() or 1)

    # Generate config
    config_path = generate_snaphu_config(
        phase_file=phase_path,
        coherence_file=coh_path,
        output_file=unwrapped_path,
        width=width,
        config_path=work_dir / "snaphu.conf",
        cost_mode=cost_mode,
        n_tile_row=n_tile_row,
        n_tile_col=n_tile_col,
        n_proc=n_proc,
        corr_threshold=corr_threshold,
    )

    # Run SNAPHU
    run_snaphu(config_path, work_dir=work_dir, snaphu_bin=snaphu_bin)

    # Read result
    return read_unwrapped_phase(unwrapped_path, height, width)
